Category/Models/ErrorViewModel.cs
namespace Category.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Category/Controllers/HomeController.cs
using Category.Domain.Interfaces;
using Category.Domain.Models;
using Category.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;

namespace Category.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Index()
        {
           var res= await _unitOfWork.CategoryRepository.GetAll();
            return View(res);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost("Create")]
        public IActionResult Create(CategoryDomain categoryDomain)
        {
            if (categoryDomain.Name == categoryDomain.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Category.Name", "Display order can not be same as Name");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.CategoryRepository.Insert(categoryDomain);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View();
        }
        [Authorize(Roles = "Admin,User")]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

Category/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Category.Domain.Models;

namespace Category.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(UserDomain userDomain)
        {
            if(!ModelState.IsValid)
            {
                ViewData["Invalid"] = "Invalid User";
                return View();

            }
            if (userDomain.UserName.ToLower() == "admin" && userDomain.Password == "admin")
            {
                List<Claim> claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.NameIdentifier, userDomain.UserName));
                claims.Add(new Claim(ClaimTypes.Name, userDomain.UserName));
                claims.Add(new Claim(ClaimTypes.Role, "Admin"));

                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                HttpContext.SignInAsync(principal);
                return RedirectToAction("Index","Home");
            }else if(userDomain.UserName.ToLower() == "user" && userDomain.Password == "user")
            {
                List<Claim> claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.NameIdentifier, userDomain.UserName));
                claims.Add(new Claim(ClaimTypes.Name, userDomain.UserName));
                claims.Add(new Claim(ClaimTypes.Role, "User"));

                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                HttpContext.SignInAsync(principal);
                return RedirectToAction("Privacy", "Home");
            }
            ModelState.AddModelError("", "Invalid Credential");
            return View();
        }


        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index");
        }
    }
}

Category/Views/Home/Create.cshtml
@model Category.Domain.Models.CategoryDomain
@{
    ViewData["Title"] = "Home Page";
}

<form method="post"  asp-action="Create" asp-controller="Home">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary pl-3">Create Category</h2>
            <br />
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <label asp-for="@Model.Name"></label>
            <input asp-for="@Model.Name" class="form-control" />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.DisplayOrder"></label>
            <input asp-for="@Model.DisplayOrder" class="form-control" />
            @*    <span asp-validation-for="@Model.Category.DisplayOrder" class="text-danger"></span> *@
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px;">Create</button>
    </div>
</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
   }

Category/Views/Home/Index.cshtml
@model IEnumerable<Category.Domain.Models.CategoryDomain>
@{
    ViewData["Title"] = "Home Page";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Category List</h2>
        </div>
        <div class="col-6 text-end">
            <a href="/Home/Create" class="btn btn-primary">
                <i class="bi bi-pencil-square"></i>&nbsp;Create New Category
            </a>
        </div>
    </div>
    <br />
    <br />
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Display Order</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ToList())
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.DisplayOrder</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Category/Views/Home/Login.cshtml
@{
    string error = ViewData["Invalid"] as string;
}
<div class="text-danger">
    @error
</div>
<form method="post" asp-action="Index" asp-controller="Login">
    <input type="text" name="username" />
    <input type="text" name="password" />
    <input type="submit" name="Submit"/>
</form>

Category/Views/Login/Index.cshtml
@model Category.Domain.Models.UserDomain


<form method="post" asp-action="Index" asp-controller="Login">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary pl-3">Login</h2>
            <br />
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <label asp-for="@Model.UserName"></label>
            <input asp-for="@Model.UserName" class="form-control" />
            <span asp-validation-for="@Model.UserName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Password"></label>
            <input asp-for="@Model.Password" class="form-control" />
            @*    <span asp-validation-for="@Model.Category.DisplayOrder" class="text-danger"></span> *@
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px;">Login</button>
    </div>
</form>

Category/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Category</title>
    <link href="~/css/bootswatch.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Category.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Category</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            var userIdentity = (ClaimsIdentity)User.Identity;
                            var claims = userIdentity.Claims;
                            var roleClaimType = userIdentity.RoleClaimType;
                            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();
                        }
                        @if (roles.Count() > 0 && roles[0].Value == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
    
                        }

                        @if (roles.Count() > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Logout">LogOut</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">LogIn</a>
                            </li>
                           
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Category - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>